In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, exc
from fuzzywuzzy import process
from datetime import datetime
import argparse
import psycopg2
import re
import pandas as pd
import IPython
from IPython.display import display, HTML

In [2]:
db_url = 'postgresql://postgres:root@localhost:5432/NAS'

In [3]:
mainYearInput = '2023-24'

In [10]:
df1 =  pd.read_excel(f'PLFSSheet.xlsx', sheet_name='Statement1-2' , dtype='str', usecols="B,C,F")

In [11]:
df1

,Unnamed: 1,Unnamed: 2,Unnamed: 5
0,NaN,NaN,NaN
1,NaN,NaN,NaN
2,NaN,NaN,NaN
3,NaN,NaN,NaN
4,NaN,NaN,NaN
...,...,...,...
83,30,Per Capita GNDI (₹),212945.5388773234
84,31,Per Capita PFCE (₹),129399.93702289378
85,RE: Revised Estimates; PE: Provisional Estimat...,NaN,NaN
86,@GDP (Production/Income Approach) = GVA at Bas...,NaN,NaN
87,"#Following Expenditure Approach, GDP = PFCE + ...",NaN,NaN

In [14]:
constantDF = df1[1:42]
currentDF = df1[45:89]

In [15]:
constantDF = constantDF.dropna(axis=0, how='any')
currentDF = currentDF.dropna(axis=0, how='any')

In [16]:
constantDF.columns = constantDF.iloc[0]
currentDF.columns = currentDF.iloc[0]

In [17]:
constantDF= pd.DataFrame(constantDF[1:])
currentDF= pd.DataFrame(currentDF[1:])

In [19]:
currentDF

56 S.No                                             Item              2023-24
59    1                              GVA at Basic Prices     26712195.2445279
60    2                            Net Taxes on Products      2945549.4905399
61    3                   Gross Domestic Product (GDP) @     29657744.7350678
62    4                       Net Domestic Product (NDP)     26558401.9107409
64    5     Private Final Consumption Expenditure (PFCE)     18051291.2146937
65    6  Government Final Consumption Expenditure (GFCE)    3045907.041345458
66    7             Gross Fixed Capital Formation (GFCF)    8832160.983819287
67    8                          Changes in Stocks (CIS)    190981.7016097566
68    9                                        Valuables   314675.27229043166
69   10                                          Exports    6428931.759793985
70   11                                          Imports    7016343.522595471
71   12                                    Discrepancies  -189859.71588934027
72   13                                              GDP    29657744.73506779
75   23                      Gross National Income (GNI)    29025946.06502848
76   24                        Net National Income (NNI)   25926603.240701586
77   25          Gross National Disposable Income (GNDI)    29705902.67338661
78   26            Net National Disposable Income (NNDI)   26606559.849059716
80   27                               Per Capita GDP (₹)   212600.32068148954
81   28                               Per Capita GNI (₹)   208071.29795719343
82   29                               Per Capita NNI (₹)   185853.78667169597
83   30                              Per Capita GNDI (₹)    212945.5388773234
84   31                              Per Capita PFCE (₹)   129399.93702289378

In [20]:
constantDF['Item'] = constantDF['Item'].apply(lambda x: x.strip())
currentDF['Item'] = currentDF['Item'].apply(lambda x: x.strip())

In [22]:
contsantArray = ['2','3','4','5','6','7','8','9','10','11','23']
currentArray =  ['2','3','4','5','6','7','8','9','10','11','23','25']

In [23]:
constantDF=constantDF[constantDF["S.No"].isin(contsantArray)].copy()
currentDF=currentDF[currentDF["S.No"].isin(currentArray)].copy()

In [24]:
constantDF

9  S.No                                             Item             2023-24
13    2                            Net Taxes on Products     1396484.7219914
14    3                   Gross Domestic Product (GDP) @    17178641.2659947
15    4                       Net Domestic Product (NDP)    14958030.2030481
17    5     Private Final Consumption Expenditure (PFCE)    9774121.69085006
18    6  Government Final Consumption Expenditure (GFCE)  1641363.6655709648
19    7             Gross Fixed Capital Formation (GFCF)  5994586.1423392445
20    8                          Changes in Stocks (CIS)  133319.14580435562
21    9                                        Valuables  197930.67183886463
22   10                                          Exports   3806953.419211607
23   11                                          Imports   4629535.855441537
27   23                      Gross National Income (GNI)   16805360.61932466

In [31]:
currentDF

56,index,S.No,Item,2023-24,approchCode
0,60,3,Net Taxes on Products,2945549.4905399,1
1,61,6,Gross Domestic Product (GDP) @,29657744.7350678,1
2,62,8,Net Domestic Product (NDP),26558401.9107409,1
3,64,11,Private Final Consumption Expenditure (PFCE),18051291.2146937,2
4,65,12,Government Final Consumption Expenditure (GFCE),3045907.041345458,2
5,66,10,Gross Fixed Capital Formation (GFCF),8832160.983819287,2
6,67,13,Changes in Stocks (CIS),190981.7016097566,2
7,68,14,Valuables,314675.27229043166,2
8,69,15,Exports,6428931.759793985,2
9,70,16,Imports,7016343.522595471,2
10,75,18,Gross National Income (GNI),29025946.06502848,None
11,77,20,Gross National Disposable Income (GNDI),29705902.67338661,None

In [32]:
currentDF["S.No"] = ['3','6','8','11','12','10','13','14','15','16','18','20']
constantDF["S.No"] = ['3','6','8','11','12','10','13','14','15','16','18']

In [33]:
currentDF["approchCode"] = ['1','1','1','2','2','2','2','2','2','2',None,None]
constantDF["approchCode"] = ['1','1','1','2','2','2','2','2','2','2',None]

In [34]:
currentDF.reset_index(inplace = True)
currentDF

56,level_0,index,S.No,Item,2023-24,approchCode
0,0,60,3,Net Taxes on Products,2945549.4905399,1
1,1,61,6,Gross Domestic Product (GDP) @,29657744.7350678,1
2,2,62,8,Net Domestic Product (NDP),26558401.9107409,1
3,3,64,11,Private Final Consumption Expenditure (PFCE),18051291.2146937,2
4,4,65,12,Government Final Consumption Expenditure (GFCE),3045907.041345458,2
5,5,66,10,Gross Fixed Capital Formation (GFCF),8832160.983819287,2
6,6,67,13,Changes in Stocks (CIS),190981.7016097566,2
7,7,68,14,Valuables,314675.27229043166,2
8,8,69,15,Exports,6428931.759793985,2
9,9,70,16,Imports,7016343.522595471,2
10,10,75,18,Gross National Income (GNI),29025946.06502848,None
11,11,77,20,Gross National Disposable Income (GNDI),29705902.67338661,None

In [35]:
constantDF.reset_index(inplace = True)
constantDF

9,level_0,index,S.No,Item,2023-24,approchCode
0,0,13,3,Net Taxes on Products,1396484.7219914,1
1,1,14,6,Gross Domestic Product (GDP) @,17178641.2659947,1
2,2,15,8,Net Domestic Product (NDP),14958030.2030481,1
3,3,17,11,Private Final Consumption Expenditure (PFCE),9774121.69085006,2
4,4,18,12,Government Final Consumption Expenditure (GFCE),1641363.6655709648,2
5,5,19,10,Gross Fixed Capital Formation (GFCF),5994586.1423392445,2
6,6,20,13,Changes in Stocks (CIS),133319.14580435562,2
7,7,21,14,Valuables,197930.67183886463,2
8,8,22,15,Exports,3806953.419211607,2
9,9,23,16,Imports,4629535.855441537,2
10,10,27,18,Gross National Income (GNI),16805360.61932466,None

In [36]:
def getFirstDigitsNumber(text):
    print(text)
    # Define a set of special characters
    splitted = text.split(" ")  # Splitting based on comma
    print(text)
    return splitted[0]

In [37]:
def remove_special_characters(text):
    # Define a set of special characters
    special_characters = "!@#$%^&*()_+{}[]|\;:'\"<>,.?/~`"

    # Use a loop to iterate through each character in the text and filter out the special characters
    cleaned_text = ''.join(char for char in text if char not in special_characters)

    return cleaned_text

In [38]:
def remove_characters(text):
    # Define a set of special characters
    special_characters = "!@#$%^&*()_-+{}[]|\;:'\"<>,.?/~`"

    # Use a loop to iterate through each character in the text and filter out the special characters
    cleaned_text = ''.join(char for char in text if char not in special_characters)

    return cleaned_text

In [39]:
pattern = r'[^a-zA-Z0-9]'  # This pattern matches all non-alphanumeric characters
year = mainYearInput.replace('-', '')
mainYear =  mainYearInput
print(year)
print(mainYear)

202324
2023-24

In [40]:
constantDF[mainYearInput]

0        1396484.7219914
1       17178641.2659947
2       14958030.2030481
3       9774121.69085006
4     1641363.6655709648
5     5994586.1423392445
6     133319.14580435562
7     197930.67183886463
8      3806953.419211607
9      4629535.855441537
10     16805360.61932466
Name: 2023-24, dtype: object

In [69]:
currentDF[mainYearInput]

0         1905133
1        19481975
2        17451892
3        11569766
4       27,24,740
5       47,23,349
6        3,33,968
7        1,37,540
8       35,34,555
9       35,05,756
10    1,92,39,492
11    1,97,74,410
Name: 2020-21, dtype: object

In [70]:
def getFirstDigitsNumber(text):
    try:
       splitted = text.split(".") 
       return str(abs(int(splitted[0]))) 
    except Exception as e:# Splitting based on comma
        return str(abs(int(text)))

In [71]:
currentDF[mainYear] = currentDF[mainYear].astype(str) 
currentDF[mainYear] = currentDF[mainYear].apply(lambda x: int(x.replace(',', '')))
print(currentDF[mainYear])

currentDF['fact_code']  = "FAE" +  year + year + currentDF['S.No']  + currentDF[mainYear].apply(getFirstDigitsNumber) + "1"

currentTransD2 = pd.DataFrame({
        'fact_code':currentDF['fact_code'],
        'year':mainYearInput,
        # 'quarter_code': '1',
        'account_code': '1',
        'approach_code': constantDF['approchCode'],
        'frequency_code': '1',
        'indicater_code': currentDF['S.No'],
        'price_at_code': '1', 
        'revision_code':  '1', 
        # 'industry_specific_code': nasFactDf['id'],
        'indicator_value': currentDF[mainYear],
        # 'amount_percentage_value': nasFactDf['percentage'],
        'created_by': 'System',
        'updated_by': 'System',
        'status': "Active"})


# engine = create_engine(db_url)
# table_name = 'nas_fact'

# currentTransD2.to_sql(table_name, engine, if_exists='append', index=False)
# print(f'Nas Fact Updated  with First Advance Estimates of National Income Sheet')

0      1905133
1     19481975
2     17451892
3     11569766
4      2724740
5      4723349
6       333968
7       137540
8      3534555
9      3505756
10    19239492
11    19774410
Name: 2020-21, dtype: int64
Nas Fact Updated  with First Advance Estimates of National Income Sheet

In [41]:
currentTransD2

NameError: name 'currentTransD2' is not defined

In [ ]:
constantDF[mainYear] = constantDF[mainYear].astype(str) 
constantDF[mainYear] = constantDF[mainYear].apply(lambda x: int(x.replace(',', '')))
print(constantDF[mainYear])

constantDF['fact_code'] = "FAE" +  year + year + constantDF['S.No'] + constantDF[mainYear].apply(getFirstDigitsNumber) + "2"


constantDFTransD2 = pd.DataFrame({
        'fact_code':constantDF['fact_code'],
        'year': mainYearInput,
        # 'quarter_code': '1',
        'account_code': '1',
        'approach_code': constantDF['approchCode'],
        'frequency_code': '1',
        'indicater_code': constantDF['S.No'],
        'price_at_code': '2', 
        'revision_code':  '1', 
        # 'industry_specific_code': nasFactDf['id'],
        'indicator_value': constantDF[mainYear],
        # 'amount_percentage_value': nasFactDf['percentage'],
        'created_by': 'System',
        'updated_by': 'System',
        'status': "Active"})

engine = create_engine(db_url)
table_name = 'nas_fact'

constantDFTransD2.to_sql(table_name, engine, if_exists='append', index=False)
print(f'Nas Fact Updated  with First Advance Estimates of National Income Sheet')

In [73]:
df1 =  pd.read_excel(f'D:/Deepak/Nas/30042024/CDRNAD/Press Notes on Advance and Provisional Estimates/{mainYearInput}/Statements First Advance Estimate.xlsx', sheet_name='Statement3-4' , dtype='str', usecols="A,B,E")

In [74]:
df1

   Unnamed: 0                                         Unnamed: 1 Unnamed: 4
0         NaN                                                NaN        NaN
1         NaN                                                NaN        NaN
2         NaN                                                NaN        NaN
3         NaN  STATEMENT  3:  F'lrst Advance Estlmates of GVA...        NaN
4        S.No                                           Industry    2020-21
5           1                   Agriculture,  Forestry & Fishing  20,13,927
6           2                                 Mining & Quarrying   3,11,621
7           3                                      Manufacniring    2098912
8           4            Electricity,  Gas, Water Supply & Other   3,17,125
9         NaN                                                NaN        NaN
10          5                                        Conshuction   9,03,243
11          6  Trade, Hotels, Transport, Communication &'Serv...  20,26,128
12          7    Financial,  Real Estate & Professional Services  28,91,811
13          8           Public Adirlinistration, Defence & Other  17,76,408
14          9                                GVA at Basic Prlces   12339175
15        NaN  PE: Provisional  Estimates. AE: Advance Estimates        NaN
16        NaN                                                NaN        NaN
17        NaN                                                NaN        NaN
18        NaN                                                NaN        NaN
19        NaN                                                NaN        NaN
20        NaN  STATEMENT  4:  First Ailvance Estimates of GVA...        NaN
21        NaN                                                NaN        NaN
22       S.No                                           Industry    2020-21
23          1                   Agriculture,  Forestry & Fislung  34,94,823
24          2                                  Mining & Qusnying   2,94,249
25          3                                      Manufacturing  25,53,708
26          4             Elechicity,  Gas, Water Supply & Otber   4,77,111
27          5                                       Construction    1213717
28          6         Trade,  Hotels, Transport, Communication &  27,11,124
29          7    Finnncinl,  Renl Estate & Professional Services    3896395
30          8    Riblic Administration, Defence & Other Services    2935715
31          9                                GVA at Basic Prices   17576842
32        NaN  PE: Provisional  Estimates; AE: Advance Estimates        NaN

In [75]:
constantIndustryDF = df1[1:17]
currentIndustryDF = df1[17:40]

In [76]:
constantIndustryDF

   Unnamed: 0                                         Unnamed: 1 Unnamed: 4
1         NaN                                                NaN        NaN
2         NaN                                                NaN        NaN
3         NaN  STATEMENT  3:  F'lrst Advance Estlmates of GVA...        NaN
4        S.No                                           Industry    2020-21
5           1                   Agriculture,  Forestry & Fishing  20,13,927
6           2                                 Mining & Quarrying   3,11,621
7           3                                      Manufacniring    2098912
8           4            Electricity,  Gas, Water Supply & Other   3,17,125
9         NaN                                                NaN        NaN
10          5                                        Conshuction   9,03,243
11          6  Trade, Hotels, Transport, Communication &'Serv...  20,26,128
12          7    Financial,  Real Estate & Professional Services  28,91,811
13          8           Public Adirlinistration, Defence & Other  17,76,408
14          9                                GVA at Basic Prlces   12339175
15        NaN  PE: Provisional  Estimates. AE: Advance Estimates        NaN
16        NaN                                                NaN        NaN

In [77]:
currentIndustryDF

   Unnamed: 0                                         Unnamed: 1 Unnamed: 4
17        NaN                                                NaN        NaN
18        NaN                                                NaN        NaN
19        NaN                                                NaN        NaN
20        NaN  STATEMENT  4:  First Ailvance Estimates of GVA...        NaN
21        NaN                                                NaN        NaN
22       S.No                                           Industry    2020-21
23          1                   Agriculture,  Forestry & Fislung  34,94,823
24          2                                  Mining & Qusnying   2,94,249
25          3                                      Manufacturing  25,53,708
26          4             Elechicity,  Gas, Water Supply & Otber   4,77,111
27          5                                       Construction    1213717
28          6         Trade,  Hotels, Transport, Communication &  27,11,124
29          7    Finnncinl,  Renl Estate & Professional Services    3896395
30          8    Riblic Administration, Defence & Other Services    2935715
31          9                                GVA at Basic Prices   17576842
32        NaN  PE: Provisional  Estimates; AE: Advance Estimates        NaN

In [78]:
constantIndustryDF = constantIndustryDF.dropna(axis=0, how='any')
currentIndustryDF = currentIndustryDF.dropna(axis=0, how='any')

In [79]:
currentIndustryDF

   Unnamed: 0                                       Unnamed: 1 Unnamed: 4
22       S.No                                         Industry    2020-21
23          1                 Agriculture,  Forestry & Fislung  34,94,823
24          2                                Mining & Qusnying   2,94,249
25          3                                    Manufacturing  25,53,708
26          4           Elechicity,  Gas, Water Supply & Otber   4,77,111
27          5                                     Construction    1213717
28          6       Trade,  Hotels, Transport, Communication &  27,11,124
29          7  Finnncinl,  Renl Estate & Professional Services    3896395
30          8  Riblic Administration, Defence & Other Services    2935715
31          9                              GVA at Basic Prices   17576842

In [80]:
constantIndustryDF.columns = constantIndustryDF.iloc[0]
currentIndustryDF.columns = currentIndustryDF.iloc[0]

In [81]:
constantIndustryDF= pd.DataFrame(constantIndustryDF[1:])
currentIndustryDF= pd.DataFrame(currentIndustryDF[1:])

In [82]:
currentIndustryDF

22 S.No                                         Industry    2020-21
23    1                 Agriculture,  Forestry & Fislung  34,94,823
24    2                                Mining & Qusnying   2,94,249
25    3                                    Manufacturing  25,53,708
26    4           Elechicity,  Gas, Water Supply & Otber   4,77,111
27    5                                     Construction    1213717
28    6       Trade,  Hotels, Transport, Communication &  27,11,124
29    7  Finnncinl,  Renl Estate & Professional Services    3896395
30    8  Riblic Administration, Defence & Other Services    2935715
31    9                              GVA at Basic Prices   17576842

In [83]:
constantIndustryDF

4  S.No                                           Industry    2020-21
5     1                   Agriculture,  Forestry & Fishing  20,13,927
6     2                                 Mining & Quarrying   3,11,621
7     3                                      Manufacniring    2098912
8     4            Electricity,  Gas, Water Supply & Other   3,17,125
10    5                                        Conshuction   9,03,243
11    6  Trade, Hotels, Transport, Communication &'Serv...  20,26,128
12    7    Financial,  Real Estate & Professional Services  28,91,811
13    8           Public Adirlinistration, Defence & Other  17,76,408
14    9                                GVA at Basic Prlces   12339175

In [84]:
constantIndustryDF['Industry'] = constantIndustryDF['Industry'].apply(lambda x: x.strip())
currentIndustryDF['Industry'] = currentIndustryDF['Industry'].apply(lambda x: x.strip())

In [85]:
# contsantIndustryArray = ['1','2','3','4','5','6','9','12','15']
contsantIndustryArray = ['1','2','3','4','5','6','7','8','9']
currentIndustryArray =  ['1','2','3','4','5','6','7','8','9']

In [86]:
constantIndustryDF=constantIndustryDF[constantIndustryDF["S.No"].isin(contsantIndustryArray)].copy()
currentIndustryDF=currentIndustryDF[currentIndustryDF["S.No"].isin(currentIndustryArray)].copy()

In [87]:
currentIndustryDF["S.No"]  =  ['5','16','15','7','6','22','9','18','21']
constantIndustryDF["S.No"] =  ['5','16','15','7','6','22','9','18','21']

In [88]:
constantIndustryDF

4  S.No                                           Industry    2020-21
5     5                   Agriculture,  Forestry & Fishing  20,13,927
6    16                                 Mining & Quarrying   3,11,621
7    15                                      Manufacniring    2098912
8     7            Electricity,  Gas, Water Supply & Other   3,17,125
10    6                                        Conshuction   9,03,243
11   22  Trade, Hotels, Transport, Communication &'Serv...  20,26,128
12    9    Financial,  Real Estate & Professional Services  28,91,811
13   18           Public Adirlinistration, Defence & Other  17,76,408
14   21                                GVA at Basic Prlces   12339175

In [89]:
currentIndustryDF

22 S.No                                         Industry    2020-21
23    5                 Agriculture,  Forestry & Fislung  34,94,823
24   16                                Mining & Qusnying   2,94,249
25   15                                    Manufacturing  25,53,708
26    7           Elechicity,  Gas, Water Supply & Otber   4,77,111
27    6                                     Construction    1213717
28   22       Trade,  Hotels, Transport, Communication &  27,11,124
29    9  Finnncinl,  Renl Estate & Professional Services    3896395
30   18  Riblic Administration, Defence & Other Services    2935715
31   21                              GVA at Basic Prices   17576842

In [90]:
header = currentIndustryDF.columns
pattern = r'[^a-zA-Z0-9]'  # This pattern matches all non-alphanumeric characters
year = mainYearInput.replace('-', '')
mainYear =  mainYearInput
print(year)
print(mainYear)

202021
2020-21

In [91]:
currentIndustryDF[mainYear] = currentIndustryDF[mainYear].astype(str) 
print(currentIndustryDF[mainYear])
currentIndustryDF[mainYear] = currentIndustryDF[mainYear].apply(lambda x: int(x.replace(',', '')))


currentIndustryDF['fact_code']  = "FAE" + year + year + currentIndustryDF['S.No']  + currentIndustryDF[mainYear].apply(getFirstDigitsNumber) + "1"

currentIndustryTransD2 = pd.DataFrame({
        'fact_code':currentIndustryDF['fact_code'],
        'year': mainYearInput,
        'account_code': '1',
        'approach_code': '1',
        'frequency_code': '1',
        'indicater_code': '1',
        'price_at_code': '1', 
        'revision_code':  '1', 
        'industry_specific_code': currentIndustryDF['S.No'],
        'indicator_value': currentIndustryDF[mainYear],
        'created_by': 'System',
        'updated_by': 'System',
        'status': "Active"})


engine = create_engine(db_url)
table_name = 'nas_fact'

currentIndustryTransD2.to_sql(table_name, engine, if_exists='append', index=False)
print(f'Nas Fact Updated  with First Advance Estimates of National Income Industry Sheet')

23    34,94,823
24     2,94,249
25    25,53,708
26     4,77,111
27      1213717
28    27,11,124
29      3896395
30      2935715
31     17576842
Name: 2020-21, dtype: object
Nas Fact Updated  with First Advance Estimates of National Income Industry Sheet

In [92]:
constantIndustryDF[mainYear] = constantIndustryDF[mainYear].astype(str) 
constantIndustryDF[mainYear] = constantIndustryDF[mainYear].apply(lambda x: int(x.replace(',', '')))
print(constantIndustryDF[mainYear])


constantIndustryDF['fact_code'] = "FAE" +  year + year + constantIndustryDF['S.No'] + constantIndustryDF[mainYear].apply(getFirstDigitsNumber) + "2"

constantIndustryDFTransD2 = pd.DataFrame({
        'fact_code':constantIndustryDF['fact_code'],
        'year': header[2],
        'account_code': '1',
        'approach_code': '1',
        'frequency_code': '1',
        'indicater_code': '1',
        'price_at_code': '2', 
        'revision_code':  '1', 
        'industry_specific_code': constantIndustryDF['S.No'],
        'indicator_value': constantIndustryDF[mainYear],
        'created_by': 'System',
        'updated_by': 'System',
        'status': "Active"})

engine = create_engine(db_url)
table_name = 'nas_fact'

constantIndustryDFTransD2.to_sql(table_name, engine, if_exists='append', index=False)
print(f'Nas Fact Updated  with First Advance Estimates of National Income Industry Sheet')

5      2013927
6       311621
7      2098912
8       317125
10      903243
11     2026128
12     2891811
13     1776408
14    12339175
Name: 2020-21, dtype: int64
Nas Fact Updated  with First Advance Estimates of National Income Industry Sheet